# Generated by Django 4.2 on 2024-06-24 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_grade_review_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
