# Generated by Django 4.2 on 2024-06-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
